# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_myappuser_user_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myappuser',
            name='user_access_token',
            field=models.CharField(default=b'default token', max_length=255, unique=True),
        ),
    ]
