# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160822_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myappuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
